default: true

# Long lines happen in READMEs (URLs, diagrams, code blocks)
MD013: false

# Allow inline HTML (sometimes used for spacing/badges)
MD033: false

# Allow duplicate headings (rare, but harmless)
MD024: false
